apiVersion: v1
kind: Service
metadata:
  name: {{ include "incidentary-bridge.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "incidentary-bridge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      appProtocol: grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
      appProtocol: http
    - name: health
      port: {{ .Values.healthCheck.port }}
      targetPort: health
      protocol: TCP
    - name: metrics
      port: {{ .Values.networkPolicy.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "incidentary-bridge.selectorLabels" . | nindent 4 }}
